import { bilingual as b } from '@/lib/i18n';
export const copy = {
  skip: b('انتقل إلى المحتوى', 'Skip to content'),
  menu: b('افتح القائمة', 'Open menu'), close: b('أغلق القائمة', 'Close menu'),
  whatsapp: b('لنتحدث عبر واتساب', 'Let’s talk on WhatsApp'),
  devWarning: b('إعداد التطوير: أضف رقم واتساب لتفعيل التواصل.', 'Development setup: add a WhatsApp number to enable contact.'),
  unavailable: b('التواصل عبر واتساب غير متاح حالياً', 'WhatsApp contact is currently unavailable'),
  studio: b('استوديو الأتمتة والذكاء الاصطناعي', 'AUTOMATION & AI STUDIO'),
  heroFirst: b('ابدأ بالأتمتة', 'Start automating.'),
  heroSecond: b('وتخلّص من العتعتة...', 'Leave repetitive work behind.'),
  work: b('شاهد أعمالنا', 'View our work'),
  heroNote: b('أنظمة مصممة حول عملك، لا العكس.', 'Systems that fit your business. Naturally.'),
  canvasTitle: b('من التكرار إلى الانسياب', 'From repetitive to effortless'),
  canvasLabel: b('سير عمل ذكي', 'AN INTELLIGENT WORKFLOW'),
  canvasFoot: b('خطوات مترابطة. عمل يمضي تلقائياً.', 'Connected steps. Work that moves itself.'),
  audienceTitle: b('وقت أقل للتكرار. مساحة أكبر للنمو.', 'Less repetition. More room to grow.'),
  audience: b('للشركات الصغيرة وصنّاع المحتوى والوكالات: نربط أدواتك ونرتّب عملياتك، لتتفرغ للعمل الذي يحتاجك فعلاً.', 'For small businesses, creators, and agencies. We connect your tools and organize your operations, so you can focus on the work that needs you.'),
  outcomes: [b('مهام متكررة أقل', 'Less repetitive work'), b('إنتاج محتوى أسرع', 'Faster content production'), b('متابعة أفضل للعملاء المحتملين', 'Better lead handling'), b('عمليات عملاء منظّمة', 'Organized customer operations'), b('أدوات مترابطة', 'Connected tools')],
  servicesEyebrow: b('01 / ما الذي نؤتمته؟', '01 / WHAT WE AUTOMATE'),
  servicesTitle: b('عملك مترابط.\nلتكن أنظمتك كذلك.', 'Your work is connected.\nYour systems should be, too.'),
  servicesDescription: b('من أول رسالة إلى آخر خطوة، نبني المسار الذي يجعل العمل أبسط.', 'From the first message to the final step, we build the connections that make work simpler.'),
  serviceCards: [
    { key: 'automation', title: b('أتمتة إجراءات العمل', 'Business process automation'), description: b('بدلاً من النسخ والمتابعة اليدوية، مسار واحد ينقل البيانات وينجز الخطوات في وقتها.', 'Replace copying, chasing, and manual updates with one connected workflow.'), detail: b('اربط الأدوات، واختصر الخطوات', 'Connect tools. Simplify the everyday.') },
    { key: 'content', title: b('أنظمة إنتاج المحتوى', 'AI content & media systems'), description: b('حوّل الفكرة إلى نص وصورة وفيديو، ضمن مسار واضح للمراجعة والنشر.', 'Move from idea to text, image, and video—with a clear path to review and publishing.'), detail: b('من الفكرة إلى النشر', 'From the brief to the publish button.') },
    { key: 'chatbots', title: b('محادثات تفهم عملك', 'Chatbots & customer communication'), description: b('إجابات من معلوماتك المعتمدة، ومتابعة منظّمة، وتسليم للفريق عند الحاجة.', 'Helpful answers from approved information, organized follow-up, and a human handoff when needed.'), detail: b('استجابة واضحة، وسياق محفوظ', 'A useful response. A connected conversation.') },
    { key: 'crm', title: b('إدارة علاقات العملاء', 'CRM design & implementation'), description: b('بيانات مرتّبة ومراحل واضحة وصلاحيات مدروسة. اعرف أين يقف كل عميل وما الخطوة التالية.', 'Clean records, clear stages, and considered permissions. Know where every customer stands.'), detail: b('صورة واحدة لعملياتك', 'One clear picture of your operations.') },
  ],
  projectsEyebrow: b('02 / أعمال مختارة', '02 / SELECTED WORK'),
  projectsTitle: b('مشكلات مألوفة.\nحلول تعمل.', 'Familiar problems.\nWorking solutions.'),
  projectsDescription: b('أمثلة من أنظمة الأتمتة التي نبنيها. بلا أسماء عملاء، وبكل تفاصيل سير العمل.', 'A closer look at the systems we build. Anonymous projects, with the process made clear.'),
  all: b('كل الأعمال', 'All work'),
  categories: { content: b('أتمتة المحتوى', 'Content automation'), chatbots: b('المساعدات الذكية', 'Chatbots'), crm: b('العملاء والعمليات', 'CRM & operations'), monitoring: b('الرصد والبيانات', 'Monitoring & data') },
  caseLink: b('اكتشف سير العمل', 'Explore the workflow'), projectOverview: b('نظرة على النظام', 'System overview'),
  approachEyebrow: b('03 / كيف نعمل', '03 / HOW WE WORK'),
  approachTitle: b('من فهم المشكلة\nإلى نظام يعمل.', 'From understanding the problem\nto a system that works.'),
  approachDescription: b('نبني معك خطوة بخطوة، ونُبقي الصورة واضحة طوال الطريق.', 'A shared process, with clarity at every step.'),
  steps: [
    { title: b('نفهم العمل', 'Understand'), description: b('نتتبع الخطوات الحالية ونحدد أين يضيع الوقت.', 'Map the current process and find where time gets lost.') },
    { title: b('نصمّم النظام', 'Design'), description: b('نرسم مساراً واضحاً يربط الأدوات والأشخاص.', 'Design a clear flow connecting your tools and people.') },
    { title: b('نبني ونختبر', 'Build and test'), description: b('ننّفذ المسار ونختبر الحالات المعتادة والاستثناءات.', 'Build the system and test everyday cases and exceptions.') },
    { title: b('نطلق وندعم', 'Launch and support'), description: b('نسلّم نظاماً موثقاً وندعم الفريق في استخدامه.', 'Launch with documentation and support your team as they use it.') },
  ],
  ctaEyebrow: b('لنبدأ بخطوة واحدة', 'LET’S START WITH ONE PROCESS'),
  ctaTitle: b('هل لديك عمل متكرر\nيستهلك وقتك؟', 'Is repetitive work\nconsuming your time?'),
  ctaDescription: b('حدّثنا عنه. سنساعدك على رؤية ما يمكن أتمتته.', 'Tell us about it. We’ll help you see what can be automated.'),
  ctaButton: b('ابدأ مشروعك عبر واتساب', 'Start your project on WhatsApp'),
  footerNote: b('نصل بين العمل اليومي والإمكانات الذكية.', 'Connecting everyday work with intelligent possibilities.'),
  rights: b('جميع الحقوق محفوظة.', 'All rights reserved.'),
  privacy: b('لا نماذج ولا أدوات تتبع. التواصل عبر واتساب يخضع لسياسة خصوصيته.', 'No forms or tracking. WhatsApp conversations follow its privacy policy.'),
  instagram: b('إنستغرام', 'Instagram'),
  back: b('العودة إلى الأعمال', 'Back to projects'),
  anonymous: b('دراسة حالة دون الكشف عن هوية العميل', 'AN ANONYMOUS CASE STUDY'),
  summary: b('النظام باختصار', 'The system at a glance'),
  problem: b('ما الذي كان يعطّل العمل؟', 'What was slowing the work down?'),
  solution: b('كيف أصبح المسار أوضح؟', 'How the system brings clarity'),
  workflow: b('هكذا يمضي العمل', 'Here’s how the work moves'),
  workflowIntro: b('من نقطة البداية إلى النتيجة، دون أن يضيع السياق بين الأدوات.', 'From the starting point to the result, with context carried between tools.'),
  capabilities: b('ما الذي ينجزه النظام؟', 'What the system handles'),
  tools: b('الأدوات والتكاملات', 'Tools & integrations'),
  comparison: b('نفس العمل. مسار أفضل.', 'The same work. A better process.'),
  before: b('قبل الأتمتة', 'Before automation'), after: b('بعد الأتمتة', 'After automation'),
  results: b('ما الذي تغيّر في العمل؟', 'What changes in day-to-day work'),
  resultsNote: b('تحسينات تشغيلية وصفية؛ لم تُزوّد هذه الدراسة بقياسات أداء موثّقة.', 'Qualitative operational improvements. Verified performance measurements were not supplied for this case study.'),
  related: b('أنظمة أخرى في المسار نفسه', 'More systems in this space'),
  notFoundEyebrow: b('404 / مسار غير مكتمل', '404 / A MISSING CONNECTION'),
  notFoundTitle: b('هذا المسار لا يصل\nإلى صفحة.', 'This path doesn’t\nlead to a page.'),
  notFoundDescription: b('قد يكون الرابط تغيّر. يمكنك العودة إلى البداية واستكشاف أعمالنا.', 'The link may have changed. Head back to the beginning and explore our work.'),
  home: b('العودة إلى البداية', 'Back to the beginning'),
  diagramKinds: { trigger: b('البداية', 'Trigger'), process: b('معالجة', 'Process'), ai: b('ذكاء اصطناعي', 'AI'), integration: b('تكامل', 'Integration'), result: b('النتيجة', 'Result') },
};
