import { bilingual as b, type Localized } from '@/lib/i18n';
import type { Workflow } from '@/lib/workflow';
export type Category = 'content' | 'chatbots' | 'crm' | 'monitoring';
export type ProjectPreview = { id: number; slug: string; title: Localized; category: Category; summary: Localized; tools: string[]; visual: string; visualLabels: Localized[] };
export type Project = ProjectPreview & { problem: Localized; solution: Localized; capabilities: Localized[]; before: Localized[]; after: Localized[]; outcomes: Localized[]; workflow: Workflow };
export const projectPreviews: ProjectPreview[] = [
  { id: 1, slug: 'multi-platform-publishing', category: 'content', title: b('نظام النشر متعدد المنصات', 'Multi-Platform Publishing System'), summary: b('أرسل المحتوى مرة واحدة، ليصل إلى قنواتك بالصيغة المناسبة لكل منها.', 'Submit once. Prepare the right version for every channel.'), tools: ['YouTube', 'Instagram', 'LinkedIn', 'Facebook'], visual: 'publishing', visualLabels: [b('محتوى واحد', 'One submission'), b('قنوات متعددة', 'Multiple channels'), b('حالة واضحة', 'A clear status')] },
  { id: 2, slug: 'youtube-shorts-engine', category: 'content', title: b('محرك إنتاج الفيديوهات القصيرة', 'Automated AI YouTube Shorts Engine'), summary: b('من فكرة مجدولة إلى فيديو قصير، مع وصف عربي ومتابعة حتى الرفع.', 'From a scheduled idea to an uploaded Short, with Arabic metadata and status monitoring.'), tools: ['YouTube', 'AI video'], visual: 'shorts', visualLabels: [b('فكرة مجدولة', 'Scheduled idea'), b('فيديو قصير', 'Generated Short'), b('رفع تلقائي', 'Auto upload')] },
  { id: 3, slug: 'character-video-generator', category: 'content', title: b('نظام فيديوهات الشخصيات', 'Character-Based Video Generator'), summary: b('صور مرجعية من التخزين السحابي تتحول إلى فيديوهات تُحفظ وتُجهّز للنشر.', 'Reference images become character-focused videos, saved and prepared for YouTube.'), tools: ['Google Drive', 'AI video', 'YouTube'], visual: 'character', visualLabels: [b('صور مرجعية', 'Reference images'), b('إنشاء الفيديو', 'Generate video'), b('حفظ وتجهيز', 'Save & prepare')] },
  { id: 4, slug: 'product-content-studio', category: 'content', title: b('استوديو محتوى المنتجات', 'AI Product Content Studio'), summary: b('صور المنتج وهويته وتوجيهك الإبداعي، تتحول إلى مواد ترويجية متعددة.', 'Product images and a creative brief become multiple promotional assets.'), tools: ['Forms', 'AI image', 'AI video'], visual: 'product', visualLabels: [b('صور المنتج', 'Product inputs'), b('توجيه إبداعي', 'Creative direction'), b('مواد ترويجية', 'Campaign assets')] },
  { id: 5, slug: 'creative-production-pipeline', category: 'content', title: b('مسار الإنتاج الإبداعي', 'AI Creative Production Pipeline'), summary: b('مسار يجمع الموجز والصور والفيديو وحالة الإنتاج في مكان واحد.', 'Connect the brief, image and video generation, storage, and production tracking.'), tools: ['AI image', 'AI video', 'Cloud storage'], visual: 'creative', visualLabels: [b('موجز منظّم', 'Structured brief'), b('إنتاج إبداعي', 'Creative production'), b('حالة الإنتاج', 'Production tracking')] },
  { id: 6, slug: 'education-instagram-assistant', category: 'chatbots', title: b('مساعد إنستغرام للقطاع التعليمي', 'Educational Instagram Assistant'), summary: b('يفهم الاستفسارات التعليمية ويتابع التسجيل والحجز، ويُصعّد الأسئلة التي تحتاج إلى الفريق.', 'Guide educational enquiries through registration and booking, with escalation for unanswered questions.'), tools: ['Instagram', 'Chatbot'], visual: 'education', visualLabels: [b('استفسار عن برنامج', 'Program enquiry'), b('إجابة معتمدة', 'Approved answer'), b('تسجيل أو حجز', 'Register or book')] },
  { id: 7, slug: 'beauty-instagram-assistant', category: 'chatbots', title: b('مساعد قطاع التجميل والتصنيع الخاص', 'Beauty & Private-Label Instagram Assistant'), summary: b('إجابات معتمدة تحفظ سياق المحادثة وتوجّه العميل، مع تحويل سلس إلى موظف.', 'Keep replies within approved information and carry conversation context into a human handoff.'), tools: ['Instagram', 'Conversation memory'], visual: 'beauty', visualLabels: [b('سؤال عن منتج', 'Product question'), b('سياق محفوظ', 'Context retained'), b('متابعة بشرية', 'Human handoff')] },
  { id: 8, slug: 'whatsapp-sms-crm', category: 'crm', title: b('مساعد واتساب والرسائل لإدارة العملاء', 'WhatsApp & SMS CRM Assistant'), summary: b('كل رسالة تصل إلى سجل العميل المناسب، وكل متابعة تبدأ من سياق واضح.', 'Every message reaches the right customer record. Every follow-up starts with context.'), tools: ['Twilio', 'WhatsApp', 'SMS', 'CRM'], visual: 'messages', visualLabels: [b('رسالة واردة', 'Incoming message'), b('سجل محدّث', 'Updated contact'), b('تسليم للفريق', 'Staff handoff')] },
  { id: 9, slug: 'assisted-content-writing', category: 'content', title: b('مسار كتابة المحتوى بمساعدة ذكية', 'AI-Assisted Content Writing Workflow'), summary: b('الفكرة تصبح موجزاً ثم مسودة قابلة للمراجعة، ولا تُعتمد إلا بموافقة بشرية.', 'Turn an idea into a brief and a revised draft, with human approval before the final document is saved.'), tools: ['Trello', 'Telegram', 'AI writing'], visual: 'writing', visualLabels: [b('فكرة وموجز', 'Idea & brief'), b('مسودة ومراجعة', 'Draft & revise'), b('اعتماد بشري', 'Human approval')] },
  { id: 10, slug: 'pharmaceutical-information-monitor', category: 'monitoring', title: b('راصد المعلومات الدوائية', 'Pharmaceutical Information Monitor'), summary: b('رصد مجدول للمستندات الجديدة، واستخراج منظّم يحفظ المعلومات في جدول.', 'Detect new documents on a schedule and save structured information to a spreadsheet.'), tools: ['Database', 'Google Sheets'], visual: 'documents', visualLabels: [b('رصد مجدول', 'Scheduled check'), b('مستند جديد', 'New document'), b('بيانات منظّمة', 'Structured record')] },
  { id: 11, slug: 'consulting-opportunity-monitor', category: 'monitoring', title: b('راصد فرص الاستشارات', 'Consulting Opportunity Monitor'), summary: b('يلتقط طلبات الاستشارة العربية ويصنّفها، لتراجع الفرص المناسبة دون ضجيج البحث.', 'Find Arabic consulting requests, classify them, and save relevant opportunities for review.'), tools: ['Social platforms', 'AI classification'], visual: 'opportunities', visualLabels: [b('طلبات استشارة', 'Consulting requests'), b('تصنيف وتصفية', 'Classify & filter'), b('فرص للمراجعة', 'Relevant opportunities')] },
  { id: 12, slug: 'crm-operations-platform', category: 'crm', title: b('منصة عمليات إدارة العملاء', 'CRM Operations Platform'), summary: b('بيانات أنظف، مراحل أوضح، وصلاحيات تنظّم الوصول إلى كل معاملة.', 'Bring clean data, clear stages, and controlled access into one operations platform.'), tools: ['CRM', 'Kanban', 'Custom portal'], visual: 'operations', visualLabels: [b('تدقيق البيانات', 'Audit the data'), b('مراحل واضحة', 'Clear stages'), b('صلاحيات مدروسة', 'Controlled access')] },
];
export const categories: Category[] = ['content', 'chatbots', 'crm', 'monitoring'];
export const projectSpans = [7, 5, 4, 4, 4, 6, 6, 4, 4, 4, 6, 6] as const;
// Add a slug only when its complete case-study data and static route are ready.
export const publishedSlugs = new Set<string>();
